name: Publish

on:
  release:
    # Run this workflow when a new GitHub release is created
    types: [released]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build sample app
        run: ./gradlew aRelease

      - name: Upload APK to Release
        run: |
          APK_PATH=$(find ./app/build/outputs/apk/release/ -maxdepth 1 -type f -name "*.apk")
          gh release upload ${{ github.event.release.tag_name }} "$APK_PATH"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
